#!/bin/sh
# Copyright (c) 2022 Praveen Kumar S

# Use the original Configuration for all containers
CONFIG_FILE="$HOME/.config/qutebrowser/config.py"

# File containing list of containers
CONTAINER_LIST="$HOME/.config/qutebrowser/containers"

# Base directory to store the containers
CONTAINER_BASE="$HOME/.browser"

# Dmenu program
DMENU="rofi -dmenu"

# Prompt for Dmenu
DMENU_PROMPT="Choose Container"

# Custom options for dmenu/rofi
DMENU_FLAGS=-no-custom # -no-custom prevents custom input in rofi


# Helper function to check if the container exists
container_exists ()
{
	test $(grep -xc "$1" "$CONTAINER_LIST") -ge 1
	return $?
}
