#!/bin/sh
# Copyright (c) 2022 Praveen Kumar S
set -e

# Include config
. $(dirname $0)/containers_config

# If container name is not passed, signal an error
if [ $# -eq 0 ] 
then
	send_msg "error" "Usage: container-rm <container-name>"
	exit 1
fi

CONTAINER_NAME="$1"
# Check if container exists
if container_exists "$CONTAINER_NAME"
then
	# Remove the base dir
	BASE_DIR="$CONTAINER_BASE/$CONTAINER_NAME"
	rm -r "$BASE_DIR"

	# Remove from list
	echo "$(grep -vx "$CONTAINER_NAME" "$CONTAINER_LIST")" > "$CONTAINER_LIST"
	send_msg "info" "Container Removed"
else
	send_msg "error" "Container doesn't exists"
	exit 1
fi

